#pragma once

#include "PropertyProxySDevice/public.h"

SDEVICE_RUNTIME_DATA_FORWARD_DECLARATION(PropertyProxy);

SDEVICE_RUNTIME_DATA_DECLARATION(PropertyProxy) { };

SDEVICE_HANDLE_DECLARATION(PropertyProxy);
SDEVICE_INTERNAL_ALIASES_DECLARATION(PropertyProxy);
